---
  - include: node_exporter.yml
    when:  exporter_name == 'node'

  - include: mysql_exporter.yml
    when:  exporter_name == 'mysql'

  - include: apache_exporter.yml
    when:  exporter_name == 'apache'

  - include: mongodb_exporter.yml
    when:  exporter_name == 'mongodb'

  - include: nginx_exporter.yml
    when:  exporter_name == 'nginx'

  - include: elasticsearch_exporter.yml
    when: exporter_name == 'elasticsearch_exporter'
